### ISSUE TITLE
一份优雅简约的简历 https://github.com/gwuhaolin/resume 仓库已经没有了

### ISSUE THREAD

**Issue by enjoyWeb** [FrontEndGitHub/FrontEndGitHub#65]
一份优雅简约的简历 https://github.com/gwuhaolin/resume 仓库已经没有了

**Comment by zhujinrui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by enjoyWeb** [comment]
╭(╯3╰)╮亲！你的信件我已经收到了，我会尽快查看的O(∩_∩)O哈！

**Comment by biaochenxuying** [comment]
> 

没就没了呗
