### ISSUE TITLE
I updated my domain on my Wordpress site and now I can't edit any pages with elementor!

### ISSUE THREAD

**Issue by cluuadia** [FrontEndGitHub/FrontEndGitHub#77]
Please help me!!!!!!! My license is active in the plug-in, I updated the site address in elementor tools, I manually activated it I don't know what to do!!

**Comment by zhujinrui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
