### ISSUE TITLE
前端资料

### ISSUE THREAD

**Issue by fotuo19882023** [FrontEndGitHub/FrontEndGitHub#79]

**Comment by Yee1023** [comment]
邮件我已收到，谢谢！！

**Comment by zhujinrui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhujinrui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yee1023** [comment]
邮件我已收到，谢谢！！
